//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public string IconName { get; set; }
        public string CreatedOn { get; set; }
        public string URL { get; set; }
        public string BtnText { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
